### ISSUE TITLE
error `https://nuxters.nuxt.com/nuxter/[username]` not found

### ISSUE THREAD

**Issue by maximepvrt** [nuxt/nuxters#26]
Impossible to show the route Atinux nuxter route https://nuxters.nuxt.com/nuxter/Atinux.
I think you need to modify the API call https://github.com/nuxt/nuxters/blob/main/pages/nuxter/%5Busername%5D.vue#L9 with the https://api.nuxt.com/contributors route

**Comment by Atinux** [comment]
It's actually in progress in https://github.com/nuxt/nuxters/tree/feat/single-page

**Comment by Atinux** [comment]
https://nuxters.nuxt.com/maximepvrt 👀
