### ISSUE TITLE
Profiles Being Publicly Accessible

### ISSUE THREAD

**Issue by mrnasil** [nuxt/nuxters#29]
I think it is possible to create a dynamic path in the format '/profile/:githubusername' to fetch the user's image and score. 
Additionally, the generated image and link can be made easily shareable on social media. The image can be dynamically generated.

**Comment by Atinux** [comment]
It's in progress @mrnasil 

See https://github.com/nuxt/nuxters/tree/feat/single-page

**Comment by mrnasil** [comment]
I am eagerly waiting. Can we also add this page or the generated og:image to the GitHub readme section?

**Comment by Atinux** [comment]
Indeed, once we are capable of generating the `og:image` with this design:
![social-image](https://github.com/nuxt/nuxters/assets/904724/ced1e24d-3edb-4a14-b814-03b723450814)
