### ISSUE TITLE
Bug: Nuxters Card for GitHub is not displayed

### ISSUE THREAD

**Issue by shinGangan** [nuxt/nuxters#65]
### 🐞 Description

The Nuxters Card that was displayed in the GitHub README is suddenly not showing up.
The URL of the OG image has been changed and we believe this may be the cause.

- before: `https://nuxters.nuxt.com/{GitHub name}/__og_image__/og.png`
- after: `https://nuxters.nuxt.com/card/{GitHub name}/og.png`

However, it is possible that the loading of `Add your Nuxter card on Github` is not completed and another problem is compounding. 
(This one will creating in another bug issue: #66 ).

### 🔗 Linked Issue

related #66 .

**Comment by maximepvrt** [comment]
Yes, we changed the url, before it was the default URL of the image generated by the [og-image](https://nuxtseo.com/og-image/getting-started/installation) module, which [changed its path](https://nuxtseo.com/og-image/migration-guide/v3#og-image-url), so we set up a proxy to avoid further disruption if the path changes in the future.

**Comment by shinGangan** [comment]
Thanks for the comment.

I tried the this URL (`nuxters.nuxt.com/card/{GitHub name}/og.png`) as a test, but it didn't improve the situation. The image is still not displayed.

**Comment by maximepvrt** [comment]
https://github.com/nuxt-modules/og-image/issues/194

Your github avatar is a PNG image, and there is an error with the new version of og-image.

nuxters.nuxt.com/card/maximepvrt/og.png => OK (jpeg avatar)
nuxters.nuxt.com/card/shinGangan/og.png => KO (png avatar)

**Comment by maximepvrt** [comment]
@shinGangan

![](https://nuxters.nuxt.com/card/shinGangan/og.png)

**Comment by shinGangan** [comment]
@maximepvrt Thank you ❤️
