### ISSUE TITLE
bug: Nuxters dialog does not finish loading

### ISSUE THREAD

**Issue by shinGangan** [nuxt/nuxters#66]
### 🐞 Description

I wanted to press the `Add your Nuxter card on Github` button and display the Nuxters Card for GitHub.
However, the image does not appear and the loading never ends.

![image](https://github.com/nuxt/nuxters/assets/44604921/93658a91-59ab-45c0-9f32-d0cf073450fa)

### 🔗 Linked Issue

related #65 .

**Comment by maximepvrt** [comment]
@Atinux an idea for this error ?

![Capture d’écran 2024-04-14 à 19 50 18](https://github.com/nuxt/nuxters/assets/1840026/ea5f6cf8-0891-45cd-adea-a4ae6aeea1cb)

https://nuxters.nuxt.com/shinGangan

**Comment by maximepvrt** [comment]
@shinGangan https://github.com/nuxt-modules/og-image/pull/201 ;-)

**Comment by shinGangan** [comment]
@maximepvrt 

Oh, thanks for opening PR. 🙏
