### ISSUE TITLE
bugs: All nuxters are not displayed on the Nuxters page.

### ISSUE THREAD

**Issue by shinGangan** [nuxt/nuxters#76]
### 🐞 Description

When I opened the [Nuxters page](https://nuxters.nuxt.com/), it seemed like not all the nuxters were displayed.

![image](https://github.com/nuxt/nuxters/assets/44604921/315294f7-f538-4510-903d-b7c753435953)

The official Nuxt documentation shows them in order.

![image](https://github.com/nuxt/nuxters/assets/44604921/63ebadd2-16f9-41ed-bae8-dae3b8582fea)

So I think there may be a problem with the Nuxters page itself, not the data.
(Did the data acquisition fail during the build?)

**Comment by kingyue737** [comment]
https://nuxters.nuxt.com/api/contributors/kingyue737 404 (Not Found)

**Comment by shinGangan** [comment]
I'm also 404.

**Comment by shinGangan** [comment]
The problem has now been resolved and was temporary.
This issue is closed.
